---
- name: DevEnv Ansible Playbook
  hosts: all
  vars:
    is_ci: "{{ lookup('env', 'CI') | default(false) | bool }}"
  vars_prompt:
    - name: github_token
      prompt: "Enter your GitHub Personal Access Token (classic) with 'repo', 'read:org', and 'write:gpg_key' scopes (press Enter to skip if already configured)"
      private: yes
      default: "{{ lookup('env', 'GH_TOKEN') | default('') }}"
    - name: user_name
      prompt: "Enter your name for GPG key (press Enter to use USER_NAME env var)"
      private: no
      default: "{{ lookup('env', 'USER_NAME') | default(lookup('env', 'USER')) }}"
    - name: user_email
      prompt: "Enter your email for GPG key (press Enter to use USER_EMAIL env var)"
      private: no
      default: "{{ lookup('env', 'USER_EMAIL') | default(lookup('env', 'USER') + '@users.noreply.github.com') }}"

  roles:
    # Git installation and configuration
    - role: git
      tags: git

    # GitHub CLI installation and configuration
    - role: github-cli
      tags: github-cli

    # Zsh installation and configuration
    - role: zsh
      tags: zsh

    # Oh My Zsh installation and configuration
    - role: ohmyzsh
      tags: ohmyzsh

    # Homebrew installation and configuration
    - role: homebrew
      tags: homebrew

    # JetBrains Mono font installation
    - role: jetbrains-mono-font
      tags: fonts

  tasks:
    - name: Include GPG tasks
      include_tasks: roles/common/tasks/gpg.yml
      tags: gpg

    # Integration tasks

    - name: Run all integration tasks
      include_tasks: roles/common/tasks/integration/main.yml
      tags: integration
