---
- name: Minimal Ansible Playbook
  hosts: all
  vars_prompt:
    - name: github_token
      prompt: "Enter your GitHub Personal Access Token (classic) with 'repo', 'read:org' scopes (press Enter to skip if already configured)"
      private: yes
      default: ""

  tasks:
    - name: Get Git version info
      command: git --version
      register: git_version
      changed_when: false
      ignore_errors: true

    - name: Check if Git is Apple version
      set_fact:
        is_apple_git: "{{ 'Apple Git' in git_version.stdout }}"
      when: git_version.rc == 0

    - name: Update Xcode Command Line Tools (if Apple Git is present)
      command: xcode-select --install
      when: is_apple_git is defined and is_apple_git
      changed_when: false
      ignore_errors: true

    - name: Install Git using Homebrew (if no Git is present)
      homebrew:
        name: git
        state: latest
      when: git_version.rc != 0

    - name: Show Git status
      debug:
        msg: |
          Git status:
          {% if git_version.rc == 0 %}
          Version: {{ git_version.stdout }}
          {% if is_apple_git %}
          Type: Apple Git (updated via Xcode Command Line Tools)
          {% else %}
          Type: Homebrew Git
          {% endif %}
          {% else %}
          Git is not installed
          {% endif %}

    - name: Ensure Homebrew bin directory is in PATH
      lineinfile:
        path: ~/.zshrc
        line: 'export PATH="/opt/homebrew/bin:$PATH"'
        create: yes
      when: is_apple_git

    - name: Get updated Git path
      command: which git
      register: git_path
      changed_when: false

    - name: Show Git version
      debug:
        msg: "Using Git: {{ git_path.stdout }} ({{ git_version.stdout }})"

    - name: Example task
      debug:
        msg: "Hello from Ansible!"

    - name: Check if GitHub CLI is installed
      command: gh --version
      register: gh_version
      changed_when: false
      ignore_errors: true

    - name: Install GitHub CLI on macOS
      homebrew:
        name: gh
        state: latest
      when: ansible_os_family == "Darwin" and gh_version.rc != 0

    - name: Install GitHub CLI on Ubuntu
      block:
        - name: Install required packages
          apt:
            name: 
              - curl
              - gpg
            state: present
            
        - name: Download GitHub CLI GPG key
          get_url:
            url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
            dest: /usr/share/keyrings/githubcli-archive-keyring.gpg
            mode: '0644'

        - name: Add GitHub CLI apt repository
          apt_repository:
            repo: deb [arch=amd64 signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main
            state: present
            filename: github-cli

        - name: Install GitHub CLI
          apt:
            name: gh
            state: latest
            update_cache: yes
      when: ansible_os_family == "Debian" and gh_version.rc != 0
      become: true

    - name: Check GitHub CLI auth status
      command: gh auth status
      register: gh_auth_status
      changed_when: false
      ignore_errors: true

    - name: Configure GitHub CLI authentication
      shell: |
        echo "{{ github_token }}" | gh auth login --with-token
      when: github_token != "" and gh_auth_status.rc != 0

    - name: Configure GitHub CLI settings
      block:
        - name: Configure git protocol preference
          command: gh config set git_protocol ssh

        - name: Configure default editor
          command: gh config set editor "code --wait"

        - name: Configure default browser
          command: gh config set browser default

        - name: Configure aliases
          command: "{{ item }}"
          loop:
            - gh alias set prc 'pr create --web --assignee @me' --clobber
            - gh alias set prv 'pr view --web' --clobber
            - gh alias set prl 'pr list --web' --clobber
            - gh alias set rv 'repo view --web' --clobber
          ignore_errors: true

        - name: Add PR template
          copy:
            dest: ~/.config/gh/pr-template.md
            content: |
              # Pull Request

              ## Changes
              {% raw %}
              {{.Message}}
              {% endraw %}
            mode: '0644'
            force: yes

        - name: Configure PR template
          command: gh config set pr.template ~/.config/gh/pr-template.md

    - name: Show GitHub CLI status
      debug:
        msg: |
          GitHub CLI status:
          {% if gh_version.rc == 0 %}
          Version: {{ gh_version.stdout }}
          {% if gh_auth_status.rc == 0 %}
          Authentication: Configured
          {% else %}
          Authentication: Not configured (token required)
          {% endif %}
          {% else %}
          GitHub CLI has been installed and configured.
          {% endif %} 