---
- name: Minimal Ansible Playbook
  hosts: all
  vars:
    is_ci: "{{ lookup('env', 'CI') | default(false) | bool }}"
  vars_prompt:
    - name: github_token
      prompt: "Enter your GitHub Personal Access Token (classic) with 'repo', 'read:org', and 'write:gpg_key' scopes (press Enter to skip if already configured)"
      private: yes
      default: "{{ lookup('env', 'GH_TOKEN') | default('') }}"
    - name: user_name
      prompt: "Enter your name for GPG key (press Enter to use USER_NAME env var)"
      private: no
      default: "{{ lookup('env', 'USER_NAME') | default(lookup('env', 'USER')) }}"
    - name: user_email
      prompt: "Enter your email for GPG key (press Enter to use USER_EMAIL env var)"
      private: no
      default: "{{ lookup('env', 'USER_EMAIL') | default(lookup('env', 'USER') + '@users.noreply.github.com') }}"

  tasks:
    - name: Include Zsh tasks
      include_tasks: roles/common/tasks/zsh.yml
      tags: zsh

    - name: Include Homebrew tasks
      include_tasks: roles/common/tasks/brew.yml
      tags: brew

    - name: Include Git tasks
      include_tasks: roles/common/tasks/git.yml

    - name: Include GPG tasks
      include_tasks: roles/common/tasks/gpg.yml

    - name: Include GitHub CLI tasks
      include_tasks: roles/common/tasks/gh.yml

    - name: Install JetBrains Mono font
      include_tasks: roles/common/tasks/fonts.yml
      tags: fonts