---
- name: DevEnv Ansible Playbook
  hosts: all
  vars:
    is_ci: "{{ lookup('env', 'CI') | default(false) | bool }}"
  vars_prompt:
    - name: github_token
      prompt: "Enter your GitHub Personal Access Token (classic) with 'repo', 'read:org', and 'write:gpg_key' scopes (press Enter to skip if already configured)"
      private: yes
      default: "{{ lookup('env', 'GH_TOKEN') | default('') }}"
    - name: user_name
      prompt: "Enter your name for GPG key (press Enter to use USER_NAME env var)"
      private: no
      default: "{{ lookup('env', 'USER_NAME') | default(lookup('env', 'USER')) }}"
    - name: user_email
      prompt: "Enter your email for GPG key (press Enter to use USER_EMAIL env var)"
      private: no
      default: "{{ lookup('env', 'USER_EMAIL') | default(lookup('env', 'USER') + '@users.noreply.github.com') }}"

  tasks:
    # Git installation and configuration tasks
    - name: Include Git tasks
      include_tasks: roles/common/tasks/git/main.yml
      tags: git

    # Homebrew installation and configuration tasks
    - name: Include Homebrew tasks
      include_tasks: roles/common/tasks/homebrew/main.yml
      tags: homebrew

    - name: Include GPG tasks
      include_tasks: roles/common/tasks/gpg.yml
      tags: gpg

    - name: Include GitHub CLI tasks
      include_tasks: roles/common/tasks/gh.yml
      tags: gh

    - name: Include Zsh tasks
      include_tasks: roles/common/tasks/zsh.yml
      tags: zsh

    - name: Include Oh My Zsh tasks
      include_tasks: roles/common/tasks/oh_my_zsh.yml
      tags: oh_my_zsh

    - name: Install JetBrains Mono font
      include_tasks: roles/common/tasks/fonts.yml
      tags: fonts

    # Integration tasks

    - name: Run all integration tasks
      include_tasks: roles/common/tasks/integration/main.yml
      tags: integration
