---
- name: Check if Zsh is installed
  command: zsh --version
  register: zsh_version
  changed_when: false
  ignore_errors: true
  when: ansible_os_family == "Darwin"
  tags: zsh

- name: Install Zsh on macOS
  homebrew:
    name: zsh
    state: latest
  when: ansible_os_family == "Darwin" and zsh_version.rc != 0
  register: zsh_install
  failed_when: zsh_install.failed
  tags: zsh

- name: Install Zsh on Ubuntu
  apt:
    name: zsh
    state: latest
  when: ansible_os_family == "Debian" and zsh_version.rc != 0
  become: true
  register: zsh_install
  failed_when: zsh_install.failed
  tags: zsh

- name: Set Zsh as default shell
  shell: chsh -s $(which zsh)
  when: ansible_os_family == "Debian" and zsh_version.rc == 0 and ansible_env.SHELL != '/bin/zsh'
  become: true
  register: chsh_config
  failed_when: chsh_config.rc != 0
  ignore_errors: true
  tags: zsh

- name: Show Zsh status
  debug:
    msg: |
      Zsh status:
      {% if zsh_version.rc == 0 %}
      Version: {{ zsh_version.stdout }}
      {% else %}
      Zsh is not installed
      {% endif %}
  when: ansible_os_family == "Debian"
  tags: zsh