- name: Check if Homebrew is already installed
  command: brew --version
  register: homebrew_check
  failed_when: false
  changed_when: false
  when: ansible_facts['os_family'] == 'Darwin'
  tags: homebrew

- name: Install Homebrew
  shell: |
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    creates: /usr/local/bin/brew
  when: ansible_facts['os_family'] == 'Darwin' and homebrew_check.rc != 0
  tags: homebrew

- name: Ensure Homebrew bin directory is in PATH
  lineinfile:
    path: ~/.zshrc
    line: 'export PATH="/opt/homebrew/bin:$PATH"'
    create: yes
  tags: homebrew

- name: Update Homebrew if already installed
  command: brew update
  when: ansible_facts['os_family'] == 'Darwin' and homebrew_check.rc == 0
  tags: homebrew
