- name: Display that the Git tasks are commencing
  debug:
    msg: "Git tasks commencing."
  tags: integration
  
- include_tasks: macos.yml
  when: ansible_os_family == "Darwin"
- include_tasks: ubuntu.yml
  when: ansible_os_family == "Debian"

# Configure the Git user
- include_tasks: config-user.yml

# Configure Git with GPG key 
- include_tasks: config-gpg.yml

- name: Display that the Git tasks are complete
  debug:
    msg: "Git tasks completed."
  tags: integration