---
- name: Check if GitHub CLI is installed
  command: gh --version
  register: gh_version
  changed_when: false
  ignore_errors: true
  tags: gh

- name: Install GitHub CLI on macOS
  homebrew:
    name: gh
    state: latest
  when: ansible_os_family == "Darwin" and gh_version.rc != 0
  tags: gh

- name: Install GitHub CLI on Ubuntu
  block:
    - name: Install required packages
      apt:
        name: 
          - curl
          - gpg
        state: present
        tags: gh
        
    - name: Download GitHub CLI GPG key
      get_url:
        url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
        dest: /usr/share/keyrings/githubcli-archive-keyring.gpg
        mode: '0644'
        tags: gh

    - name: Add GitHub CLI apt repository
      apt_repository:
        repo: deb [arch=amd64 signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main
        state: present
        filename: github-cli
        tags: gh

    - name: Install GitHub CLI
      apt:
        name: gh
        state: latest
        update_cache: yes
        tags: gh
  when: ansible_os_family == "Debian" and gh_version.rc != 0
  become: true
  tags: gh

- name: Check GitHub CLI auth status
  command: gh auth status
  register: gh_auth_status
  changed_when: false
  ignore_errors: true
  tags: gh

- name: Configure GitHub CLI authentication
  shell: |
    echo "{{ github_token }}" | gh auth login --with-token
  when: github_token != "" and gh_auth_status.rc != 0
  tags: gh

- name: Configure GitHub CLI settings
  block:
    - name: Configure git protocol preference
      command: gh config set git_protocol ssh
      tags: gh

    - name: Configure default editor
      command: gh config set editor "code --wait"
      tags: gh

    - name: Configure default browser
      command: "{{ item }}"
      loop:
        - gh config set browser "{{ 'open' if ansible_os_family == 'Darwin' else 'xdg-open' }}"
      when: not is_ci
      tags: gh

    - name: Configure aliases
      command: "{{ item }}"
      loop:
        - gh alias set prc 'pr create --web --assignee @me' --clobber
        - gh alias set prv 'pr view --web' --clobber
        - gh alias set prl 'pr list --web' --clobber
        - gh alias set rv 'repo view --web' --clobber
      ignore_errors: true
      tags: gh

    - name: Add PR template
      copy:
        dest: ~/.config/gh/pr-template.md
        content: |
          # Pull Request

          ## Changes
          {% raw %}
          {{.Message}}
          {% endraw %}
        mode: '0644'
        force: yes
      tags: gh

    - name: Configure PR template
      command: gh config set pr.template ~/.config/gh/pr-template.md
      tags: gh
  tags: gh

- name: Show GitHub CLI status
  debug:
    msg: |
      GitHub CLI status:
      {% if gh_version.rc == 0 %}
      Version: {{ gh_version.stdout }}
      {% if gh_auth_status.rc == 0 %}
      Authentication: Configured
      {% else %}
      Authentication: Not configured (token required)
      {% endif %}
      {% else %}
      GitHub CLI has been installed and configured.
      {% endif %}
  tags: gh