- include_role:
    name: homebrew
  when: ansible_os_family == "Darwin"
  tags: github-cli

- include_role:
    name: gpg
  when: ansible_os_family == "Darwin"
  tags: github-cli

- name: Check if GitHub CLI is installed
  command: gh --version
  register: gh_version
  changed_when: false
  ignore_errors: true
  when: ansible_os_family == "Darwin"
  tags: github-cli

- name: Install GitHub CLI on macOS
  homebrew:
    name: gh
    state: latest
  when: ansible_os_family == "Darwin" and gh_version.rc != 0
  tags: github-cli
