- name: Install GitHub CLI on Ubuntu
  block:
    - name: Install required packages
      apt:
        name: 
          - curl
          - gpg
        state: present
        tags: github-cli
        
    - name: Download GitHub CLI GPG key
      get_url:
        url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
        dest: /usr/share/keyrings/githubcli-archive-keyring.gpg
        mode: '0644'
        tags: github-cli

    - name: Add GitHub CLI apt repository
      apt_repository:
        repo: deb [arch=amd64 signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main
        state: present
        filename: github-cli
        tags: github-cli

    - name: Install GitHub CLI
      apt:
        name: gh
        state: latest
        update_cache: yes
        tags: github-cli
  when: ansible_os_family == "Debian" and gh_version.rc != 0
  become: true
  tags: github-cli
