name: Test Ansible Playbook

on:
  push:
    branches: 
      - master
      - 'feat/**'
  pull_request:
    branches: 
      - master
      - 'feat/**'

jobs:
  test:
    name: Test Playbook
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Run Playbook
      env:
        USER_NAME: ${{ vars.USER_NAME }}
        USER_EMAIL: ${{ vars.USER_EMAIL }}
      run: |
        ansible-playbook -i inventory.yml playbook.yml

    - name: Verify Git Installation
      run: |
        git --version
        if [ "${{ runner.os }}" == "macOS" ]; then
          which git
        fi

    - name: Verify GitHub CLI Installation and Auth
      run: |
        gh --version
        gh auth status

    - name: Verify Zsh Installation
      run: |
        zsh --version
        which zsh 