name: Test Ansible Playbook

on:
  push:
    branches: 
      - master
      - 'feat/**'
  pull_request:
    branches: 
      - master
      - 'feat/**'

jobs:
  test:
    name: Test Playbook
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:

    # Checkout

    - uses: actions/checkout@v4

    # Setup Python
    
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    # Install Ansible

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    # Run Playbook

    - name: Run Playbook
      env:
        USER_NAME: ${{ vars.USER_NAME }}
        USER_EMAIL: ${{ vars.USER_EMAIL }}
      run: |
        ansible-playbook -i inventory.yml playbook.yml

    # Verify tasks
    
    # git

    - name: Verify Git Installation
      run: |
        git --version
        which git

    # gh  

    - name: Verify GitHub CLI Installation and Auth
      run: |
        gh --version
        gh auth status

    # fonts

    - name: Verify JetBrains Mono Font Installation
      if: runner.os == 'macOS'
      run: |
        if [ -f "$HOME/Library/Fonts/JetBrainsMono-Regular.ttf" ]; then
          echo "JetBrains Mono font is installed"
        else
          echo "JetBrains Mono font is not installed"
          exit 1
        fi

    # zsh
    
    - name: Verify Zsh Installation
      run: |
        zsh --version
        which zsh

    - name: Verify Oh My Zsh Installation
      run: |
        if [ -d ~/.oh-my-zsh ]; then
          echo "Oh My Zsh is installed"
          cat ~/.oh-my-zsh/oh-my-zsh.sh | head -n 1
        else
          echo "Oh My Zsh is not installed"
          exit 1
        fi
